### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by dill** [dill/spatlaugh#1]
Things to do!
- [x] switch gradient
- [ ] weather covariate
- [ ] reduce number of observations (until it goes bleurgh)
- [x] flat surface (what happens)
- [ ] more designs (but don't go overboard) ("IWC")

To measure:
- [x] report bias and variance
